#!/bin/bash

lupdate-pro "ComputreeGui\ComputreeGui.pro"
lupdate-pro "library\ctlibcore\ctlibcore.pro"
lupdate-pro "library\ctlibexporter\ctlibexporter.pro"
lupdate-pro "library\ctlibfilters\ctlibfilters.pro"
lupdate-pro "library\ctlibio\ctlibio.pro"
lupdate-pro "library\ctliblas\ctliblas.pro"
lupdate-pro "library\ctliblaz\ctliblaz.pro"
lupdate-pro "library\ctliblog\ctliblog.pro"
lupdate-pro "library\ctlibmath\ctlibmath.pro"
lupdate-pro "library\ctlibmetrics\ctlibmetrics.pro"
lupdate-pro "library\ctlibmodelsextraviews\ctlibmodelsextraviews.pro"
lupdate-pro "library\ctlibpcl\ctlibpcl.pro"
lupdate-pro "library\ctlibplugin\ctlibplugin.pro"
lupdate-pro "library\ctlibreader\ctlibreader.pro"
lupdate-pro "library\ctlibstdactions\ctlibstdactions.pro"
lupdate-pro "library\ctlibstep\ctlibstep.pro"
lupdate-pro "library\ctlibstepaddon\ctlibstepaddon.pro"
lupdate-pro "library\ctlibstructure\ctlibstructure.pro"
lupdate-pro "library\ctlibstructureaddon\ctlibstructureaddon.pro"
lupdate-pro "library\ctlibstructurewidget\ctlibstructurewidget.pro"
lupdate-pro "library\ctlibwidget\ctlibwidget.pro"
lupdate-pro "plugins\pluginbase\pluginbase.pro"
lupdate-pro "..\plugingenerate\plugingenerate\plugingenerate.pro"
lupdate-pro "..\pluginignlif\pluginignlif\pluginignlif.pro"
lupdate-pro "..\pluginmk\pluginmk\pluginmk.pro"
lupdate-pro "..\pluginlvox\pluginlvox\pluginlvox.pro"
lupdate-pro "..\pluginonf\pluginonf\pluginonf.pro"
lupdate-pro "..\pluginonfdev\pluginonfdev\pluginonfdev.pro"
lupdate-pro "..\pluginsegma\pluginsegma\pluginsegma.pro"
lupdate-pro "..\plugintoolkit\plugintoolkit\plugintoolkit.pro"

# lupdate-pro "library\ctlibaction\ctlibaction.pro"
# lupdate-pro "library\ctlibclouds\ctlibclouds.pro"
# lupdate-pro "library\ctlibmodels\ctlibmodels.pro"
